# Generated by Django 3.0.6 on 2020-05-27 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=5, verbose_name='Giới tính')),
            ],
            options={
                'verbose_name_plural': 'Giới tính',
                'ordering': ['name'],
            },
        ),
    ]
