# Generated by Django 3.0.6 on 2020-05-27 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100, verbose_name='Tên cơ sở')),
                ('phonenumber', models.CharField(default='', max_length=100, null=True, verbose_name='SDT')),
                ('email', models.CharField(default='', max_length=100, null=True, verbose_name='Email')),
                ('adress', models.CharField(default='', max_length=300, null=True, verbose_name='Địa chỉ')),
                ('note', models.CharField(default='', max_length=300, null=True, verbose_name='Ghi chú')),
                ('active', models.BooleanField(default=True, verbose_name='Trạng thái')),
            ],
            options={
                'verbose_name_plural': 'Chi nhánh',
                'ordering': ['fullname'],
            },
        ),
        migrations.CreateModel(
            name='TimeShift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100, verbose_name='Tên ca học')),
                ('infomation', models.CharField(max_length=1000, verbose_name='Thông tin ca học')),
                ('timestart', models.TimeField(null=True, verbose_name='Giờ bắt đầu')),
                ('timeend', models.TimeField(null=True, verbose_name='Giờ kết thúc')),
                ('active', models.BooleanField(default=True, verbose_name='Trạng thái')),
            ],
            options={
                'verbose_name_plural': 'Ca học',
                'ordering': ['fullname'],
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100, verbose_name='Tên khóa học')),
                ('infomation', models.CharField(max_length=1000, null=True, verbose_name='Thông tin khóa học')),
                ('fee', models.IntegerField(default=0, verbose_name='Học phí khóa học')),
                ('active', models.BooleanField(default=True, verbose_name='Trạng thái')),
            ],
            options={
                'verbose_name_plural': 'Khóa học',
                'ordering': ['fullname'],
            },
        ),
    ]
