# Generated by Django 3.0.6 on 2020-05-27 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_area_timeshift_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='note',
            field=models.CharField(blank=True, default='', max_length=300, null=True, verbose_name='Ghi chú'),
        ),
    ]
