# Generated by Django 3.0.6 on 2020-05-27 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20200527_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='adress',
            field=models.CharField(blank=True, default='', max_length=300, null=True, verbose_name='Địa chỉ'),
        ),
        migrations.AlterField(
            model_name='area',
            name='email',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='area',
            name='phonenumber',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='SDT'),
        ),
        migrations.AlterField(
            model_name='timeshift',
            name='infomation',
            field=models.CharField(blank=True, max_length=1000, verbose_name='Thông tin ca học'),
        ),
        migrations.AlterField(
            model_name='timeshift',
            name='timeend',
            field=models.TimeField(blank=True, null=True, verbose_name='Giờ kết thúc'),
        ),
        migrations.AlterField(
            model_name='timeshift',
            name='timestart',
            field=models.TimeField(blank=True, null=True, verbose_name='Giờ bắt đầu'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='infomation',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Thông tin khóa học'),
        ),
    ]
