# Generated by Django 3.0.6 on 2020-05-27 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20200527_1640'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classname',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100, verbose_name='Tên lớp học')),
                ('startdate', models.DateField(auto_now_add=True, verbose_name='Ngày bắt đầu')),
                ('note', models.CharField(blank=True, max_length=300, null=True, verbose_name='Ghi chú')),
                ('active', models.BooleanField(default=True, verbose_name='Trạng thái')),
            ],
            options={
                'verbose_name_plural': 'Lớp học',
                'ordering': ['fullname'],
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100, verbose_name='Tên giáo viên')),
                ('birthday', models.DateField(verbose_name='Ngày sinh')),
                ('identity_card', models.CharField(blank=True, max_length=100, null=True, verbose_name='CMND')),
                ('phonenumber', models.CharField(blank=True, max_length=100, null=True, verbose_name='SDT')),
                ('email', models.CharField(blank=True, max_length=100, null=True, verbose_name='Email')),
                ('adress', models.CharField(blank=True, max_length=300, null=True, verbose_name='Địa chỉ')),
                ('create_date', models.DateField(auto_now_add=True, verbose_name='Ngày tạo thông tin')),
                ('note', models.CharField(blank=True, max_length=300, null=True, verbose_name='Ghi chú')),
                ('active', models.BooleanField(default=True, verbose_name='Trạng thái')),
                ('gender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.Gender')),
            ],
            options={
                'verbose_name_plural': 'Giáo viên',
                'ordering': ['fullname'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100, verbose_name='Tên học sinh')),
                ('birthday', models.DateField(verbose_name='Ngày sinh')),
                ('identity_card', models.CharField(max_length=100, null=True, verbose_name='CMND')),
                ('phonenumber', models.CharField(max_length=100, null=True, verbose_name='SDT')),
                ('phonenumber_family', models.CharField(max_length=100, null=True, verbose_name='SDT phụ huynh')),
                ('email', models.CharField(max_length=100, null=True, verbose_name='Email')),
                ('adress', models.CharField(max_length=300, null=True, verbose_name='Địa chỉ')),
                ('fee', models.IntegerField(default=0, verbose_name='Học phí')),
                ('fee_remain', models.IntegerField(default=0, verbose_name='Học phí còn lại')),
                ('create_date', models.DateField(auto_now_add=True, verbose_name='Ngày đăng ký học')),
                ('note', models.CharField(max_length=300, null=True, verbose_name='Ghi chú')),
                ('active', models.BooleanField(default=True, verbose_name='Trạng thái')),
                ('classname', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.Classname')),
                ('gender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.Gender')),
            ],
            options={
                'verbose_name_plural': 'Học sinh',
                'ordering': ['fullname'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100, verbose_name='Tên phòng')),
                ('active', models.BooleanField(default=True, verbose_name='Trạng thái')),
                ('erea', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.Area')),
            ],
            options={
                'verbose_name_plural': 'Phòng',
                'ordering': ['fullname'],
            },
        ),
        migrations.AddField(
            model_name='classname',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.Room'),
        ),
        migrations.AddField(
            model_name='classname',
            name='timeshift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.TimeShift'),
        ),
        migrations.AddField(
            model_name='classname',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.Unit'),
        ),
    ]
