# Generated by Django 3.0.6 on 2020-05-27 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20200527_2222'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeWeek',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Loại')),
            ],
            options={
                'verbose_name_plural': 'Ngày học trong tuần',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='classname',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.Room'),
        ),
        migrations.AlterField(
            model_name='classname',
            name='startdate',
            field=models.DateField(auto_now_add=True, verbose_name='Ngày bắt đầu học'),
        ),
        migrations.AlterField(
            model_name='classname',
            name='timeshift',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.TimeShift'),
        ),
        migrations.AlterField(
            model_name='classname',
            name='unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.Unit'),
        ),
        migrations.AlterField(
            model_name='room',
            name='erea',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.Area'),
        ),
        migrations.AlterField(
            model_name='student',
            name='classname',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.Classname'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='gender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.Gender'),
        ),
        migrations.AddField(
            model_name='classname',
            name='timeweek',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.TimeWeek'),
        ),
    ]
