# Generated by Django 3.0.6 on 2020-05-28 02:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20200527_2303'),
    ]

    operations = [
        migrations.AddField(
            model_name='classname',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.Teacher'),
        ),
    ]
