# Generated by Django 2.2.8 on 2020-05-24 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_auto_20200522_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.CharField(default='Nam', max_length=20, verbose_name='Giới tính'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='phone_number_1',
            field=models.CharField(max_length=12, verbose_name='Số điện thoại phụ huynh'),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone_number_2',
            field=models.CharField(blank=True, default='', max_length=12, null=True, verbose_name='Số điện thoại'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='birthdate',
            field=models.DateField(verbose_name='Ngày sinh'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='is_male',
            field=models.BooleanField(default=False, verbose_name='Giới tính (Nam)'),
        ),
    ]
