# Generated by Django 2.2.8 on 2020-05-25 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_auto_20200524_2235'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='fee',
            field=models.IntegerField(blank=True, default=0, verbose_name='Học phí khóa học'),
        ),
        migrations.AddField(
            model_name='student',
            name='fee_remain',
            field=models.IntegerField(blank=True, default=0, verbose_name='Học phí đã đóng'),
        ),
        migrations.AlterField(
            model_name='fee',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Stu_fee', to='student.Student'),
        ),
    ]
